name: Stock Scanner (Manual)

on:
  workflow_dispatch:
    inputs:
      full_scan:
        description: 'Run Full Scan'
        type: boolean
        required: false
        default: false
      watchlist:
        description: 'Comma separated WATCHLIST'
        type: string
        required: false
        default: ''

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create empty .env file
        run: touch .env

      - name: Run stock scanner
        env:
          GOOGLE_CHAT_WEBHOOK: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          TASTYTRADE_CLIENT_SECRET: ${{ secrets.TASTYTRADE_CLIENT_SECRET }}
          TASTYTRADE_REFRESH_TOKEN: ${{ secrets.TASTYTRADE_REFRESH_TOKEN }}
          TASTYTRADE_WATCHLISTS: ${{ vars.TASTYTRADE_WATCHLISTS }}
          WATCHLIST: ${{ inputs.watchlist != '' && inputs.watchlist || vars.WATCHLIST }}
        run: |
          ARGS="--skip-history"
          if [ "${{ github.event.inputs.full_scan }}" == "true" ]; then ARGS="$ARGS --full-scan"; fi
          npm run scan -- $ARGS
